vim.pack.add({"https://github.com/ibhagwan/fzf-lua"})
vim.pack.add({"https://github.com/nvim-tree/nvim-web-devicons"})

vim.keymap.set("n", "<leader>ff", function() require("fzf-lua").files() end, {desc = "find files"})
vim.keymap.set("n", "<leader>fz", function() require("fzf-lua").zoxide() end, {desc = "find files (zoxide)"})
vim.keymap.set("n", "<leader>fh", function() require("fzf-lua").history() end, {desc = "file history"})

vim.keymap.set("n", "<leader>llr", function() require("fzf-lua").lsp_references() end, {desc = "lsp references"})
vim.keymap.set("n", "<leader>lld", function() require("fzf-lua").lsp_definitions() end, {desc = "lsp definitions"})
vim.keymap.set("n", "<leader>llD", function() require("fzf-lua").lsp_declarations() end, {desc = "lsp declarations"})
vim.keymap.set("n", "<leader>llt", function() require("fzf-lua").lsp_typedefs() end, {desc = "lsp type definitions"})
vim.keymap.set("n", "<leader>lli", function() require("fzf-lua").lsp_implementations() end, {desc = "lsp implementations"})
vim.keymap.set("n", "<leader>lls", function() require("fzf-lua").lsp_document_symbols() end, {desc = "lsp document symbols"})
vim.keymap.set("n", "<leader>llS", function() require("fzf-lua").lsp_workspace_symbols() end, {desc = "lsp workspace symbols"})
vim.keymap.set("n", "<leader>llw", function() require("fzf-lua").lsp_live_workspace_symbols() end, {desc = "lsp workspace symbols (live query)"})
vim.keymap.set("n", "<leader>llI", function() require("fzf-lua").lsp_incoming_calls() end, {desc = "lsp incoming calls"})
vim.keymap.set("n", "<leader>llO", function() require("fzf-lua").lsp_outgoing_calls() end, {desc = "lsp outgoing calls"})
vim.keymap.set("n", "<leader>llz", function() require("fzf-lua").lsp_type_sub() end, {desc = "lsp sub types"})
vim.keymap.set("n", "<leader>llZ", function() require("fzf-lua").lsp_type_super() end, {desc = "lsp super types"})
vim.keymap.set("n", "<leader>lla", function() require("fzf-lua").lsp_code_actions() end, {desc = "lsp code Actions"})
vim.keymap.set("n", "<leader>lll", function() require("fzf-lua").lsp_finder() end, {desc = "lsp all LSP locations, combined view"})
vim.keymap.set("n", "<leader>llx", function() require("fzf-lua").diagnostics_document() end, {desc = "lsp document Diagnostics"})
vim.keymap.set("n", "<leader>llX", function() require("fzf-lua").diagnostics_workspace() end, {desc = "lsp workspace Diagnostics"})

vim.keymap.set("n", "<leader>mR", function() require("fzf-lua").resume() end, {desc = "Resume last command/query"})
vim.keymap.set("n", "<leader>mb", function() require("fzf-lua").builtin() end, {desc = "Fzf-lua builtin commands"})
vim.keymap.set("n", "<leader>mh", function() require("fzf-lua").helptags() end, {desc = "Help tags"})
vim.keymap.set("n", "<leader>mp", function() require("fzf-lua").manpages() end, {desc = "Man pages"})
vim.keymap.set("n", "<leader>mt", function() require("fzf-lua").colorschemes() end, {desc = "Color schemes"})
vim.keymap.set("n", "<leader>mT", function() require("fzf-lua").awesome_colorschemes() end, {desc = "awesome Neovim color schemes"})
vim.keymap.set("n", "<leader>mh", function() require("fzf-lua").highlights() end, {desc = "Highlight groups"})
vim.keymap.set("n", "<leader>mc", function() require("fzf-lua").commands() end, {desc = "Neovim commands"})
vim.keymap.set("n", "<leader>mC", function() require("fzf-lua").command_history() end, {desc = "Command history"})
vim.keymap.set("n", "<leader>ms", function() require("fzf-lua").search_history() end, {desc = "Search history"})
vim.keymap.set("n", "<leader>mm", function() require("fzf-lua").marks() end, {desc = ":marks"})
vim.keymap.set("n", "<leader>mj", function() require("fzf-lua").jumps() end, {desc = ":jumps"})
vim.keymap.set("n", "<leader>mr", function() require("fzf-lua").registers() end, {desc = ":registers"})
vim.keymap.set("n", "<leader>mo", function() require("fzf-lua").nvim_options() end, {desc = "Neovim options"})
vim.keymap.set("n", "<leader>mk", function() require("fzf-lua").keymaps() end, {desc = "Key mappings"})
vim.keymap.set("n", "<leader>mf", function() require("fzf-lua").filetypes() end, {desc = "Filetypes"})
vim.keymap.set("n", "<leader>mM", function() require("fzf-lua").menus() end, {desc = "Menus"})
vim.keymap.set("n", "<leader>mx", function() require("fzf-lua").spellcheck() end, {desc = "Misspelled words in buffer"})
vim.keymap.set("n", "<leader>mX", function() require("fzf-lua").spell_suggest() end, {desc = "Spelling suggestions"})
vim.keymap.set("n", "<leader>mP", function() require("fzf-lua").packadd() end, {desc = ":packadd"})
vim.keymap.set("n", "<leader>mu", function() require("fzf-lua").undotree() end, {desc = "History undo tree"})

vim.keymap.set("n", "<leader>ddc", function() require("fzf-lua").dap_commands() end, {desc = "dap List,run nvim-dap builtin commands"})
vim.keymap.set("n", "<leader>ddC", function() require("fzf-lua").dap_configurations() end, {desc = "dap List,run debug configurations"})
vim.keymap.set("n", "<leader>ddb", function() require("fzf-lua").dap_breakpoints() end, {desc = "dap List,delete breakpoints"})
vim.keymap.set("n", "<leader>ddv", function() require("fzf-lua").dap_variables() end, {desc = "dap Active session variables"})
vim.keymap.set("n", "<leader>ddf", function() require("fzf-lua").dap_frames() end, {desc = "dap Active session jump to frame"})
